from django.urls import path
from . import views
from . import telegram as tg

urlpatterns = [
    path('accounts/', views.AccountListCreateView.as_view(), name='moneyger-accounts'),
    path('accounts/<int:pk>/', views.AccountDetailView.as_view(), name='moneyger-account-detail'),
    path('accounts/<int:pk>/pay-bill/', views.AccountPayBillView.as_view(), name='moneyger-account-pay-bill'),
    path('accounts/<int:pk>/import-statement/', views.AccountImportStatementView.as_view(), name='moneyger-account-import-statement'),
    path('reset/', views.ResetDataView.as_view(), name='moneyger-reset'),
    path('categories/', views.CategoryListCreateView.as_view(), name='moneyger-categories'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='moneyger-category-detail'),
    path('transactions/', views.TransactionListCreateView.as_view(), name='moneyger-transactions'),
    path('transactions/<int:pk>/', views.TransactionDetailView.as_view(), name='moneyger-transaction-detail'),
    path('budgets/', views.BudgetListCreateView.as_view(), name='moneyger-budgets'),
    path('budgets/<int:pk>/', views.BudgetDetailView.as_view(), name='moneyger-budget-detail'),
    path('market-lists/', views.MarketListListCreateView.as_view(), name='moneyger-market-lists'),
    path('market-lists/<int:pk>/', views.MarketListDetailView.as_view(), name='moneyger-market-list-detail'),
    path('market-lists/<int:pk>/start/', views.MarketListStartView.as_view(), name='moneyger-market-list-start'),
    path('market-lists/<int:pk>/complete/', views.MarketListCompleteView.as_view(), name='moneyger-market-list-complete'),
    path('market-lists/<int:pk>/to-transaction/', views.MarketListToTransactionView.as_view(), name='moneyger-market-list-to-tx'),
    path('market-lists/<int:pk>/cancel/', views.MarketListCancelView.as_view(), name='moneyger-market-list-cancel'),
    path('market-lists/<int:pk>/items/', views.MarketListItemCreateView.as_view(), name='moneyger-market-list-items'),
    path('market-lists/<int:pk>/items/<int:item_id>/', views.MarketListItemDetailView.as_view(), name='moneyger-market-list-item'),
    path('market-lists/<int:pk>/items/<int:item_id>/check/', views.MarketListItemCheckView.as_view(), name='moneyger-market-list-item-check'),
    path('recurring/', views.RecurringListCreateView.as_view(), name='moneyger-recurring'),
    path('recurring/<int:pk>/', views.RecurringDetailView.as_view(), name='moneyger-recurring-detail'),
    path('installments/', views.InstallmentListCreateView.as_view(), name='moneyger-installments'),
    path('installments/<int:pk>/', views.InstallmentDetailView.as_view(), name='moneyger-installment-detail'),
    path('installments/<int:pk>/pay/', views.InstallmentPayView.as_view(), name='moneyger-installment-pay'),
    path('inbox/', views.InboxListView.as_view(), name='moneyger-inbox'),
    path('inbox/<int:pk>/confirm/', views.InboxConfirmView.as_view(), name='moneyger-inbox-confirm'),
    path('inbox/<int:pk>/dismiss/', views.InboxDismissView.as_view(), name='moneyger-inbox-dismiss'),
    path('inbox/<int:pk>/attachment/', views.InboxAttachmentView.as_view(), name='moneyger-inbox-attachment'),
    path('parse/', views.ParseCaptureView.as_view(), name='moneyger-parse'),
    path('capture/', views.QuickCaptureView.as_view(), name='moneyger-capture'),
    path('dashboard/', views.DashboardView.as_view(), name='moneyger-dashboard'),
    path('telegram/link-code/', tg.TelegramLinkCodeView.as_view(), name='moneyger-tg-link'),
    path('telegram/status/', tg.TelegramStatusView.as_view(), name='moneyger-tg-status'),
    path('telegram/webhook/', tg.TelegramWebhookView.as_view(), name='moneyger-tg-webhook'),
]
