# Generated by Django 5.2 on 2026-03-29 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wellhub_enabled',
            field=models.BooleanField(default=False, help_text='Ativa integração com Wellhub para geofencing'),
        ),
        migrations.CreateModel(
            name='GymLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da academia (ex: Academia Fitness, CrossFit)', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude da academia', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude da academia', max_digits=9)),
                ('is_primary', models.BooleanField(default=False, help_text='Academia padrão para geofencing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localização de Academia',
                'verbose_name_plural': 'Localizações de Academias',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
