# Generated by Django 5.2 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wellhub_enabled_gymlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Usuário aceitou os termos de isenção de responsabilidade'),
        ),
    ]
