# Generated by Django 5.2 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_adminisgrana_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_administreino_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='max_ai_generations_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='max_routines',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
