# Generated by Django 5.2 on 2026-09-17 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('cash', 'Dinheiro'), ('credit', 'Cartão de crédito'), ('other', 'Outro')], default='checking', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(blank=True, default='#22c55e', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita')], default='expense', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(blank=True, default='#22c55e', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null = categoria padrão do sistema (seed).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('limit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_budgets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='moneyger.category')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('transfer', 'Transferência')], default='expense', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensal'), ('weekly', 'Semanal'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('next_due_on', models.DateField()),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('other', 'Outro')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='moneyger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneyger.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_recurring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_on'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('link_code', models.CharField(blank=True, default='', max_length=12)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_telegram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('income', 'Receita'), ('transfer', 'Transferência')], default='expense', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_on', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('other', 'Outro')], default='other', max_length=20)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('telegram', 'Telegram'), ('import', 'Importação'), ('parser', 'Parser'), ('recurring', 'Recorrente')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('pending', 'Pendente')], default='confirmed', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='moneyger/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='moneyger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='moneyger.category')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='moneyger.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('dismissed', 'Descartado')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('telegram', 'Telegram'), ('import', 'Importação'), ('parser', 'Parser'), ('recurring', 'Recorrente')], default='parser', max_length=20)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='moneyger/inbox/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_inbox', to=settings.AUTH_USER_MODEL)),
                ('resulting_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_inbox', to='moneyger.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_active'], name='moneyger_ac_user_id_bdbb69_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'kind'), name='moneyger_category_user_name_kind_uniq'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'year', 'month'), name='moneyger_budget_user_cat_period_uniq'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='moneyger_budget_month_valid'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'occurred_on'], name='moneyger_tr_user_id_50a3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='moneyger_tr_user_id_05c960_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='moneyger_tx_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='inboxitem',
            index=models.Index(fields=['user', 'status'], name='moneyger_in_user_id_bef89f_idx'),
        ),
    ]
