# Generated by Django 5.2 on 2026-09-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringrule',
            name='nature',
            field=models.CharField(choices=[('fixed', 'Despesa fixa'), ('income_fixed', 'Receita fixa')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_installments', models.PositiveIntegerField()),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('start_on', models.DateField()),
                ('next_due_on', models.DateField()),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('other', 'Outro')], default='credit', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='moneyger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneyger.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_installments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_installments__gte', 1)), name='moneyger_installment_total_gte_1'), models.CheckConstraint(condition=models.Q(('paid_installments__gte', 0)), name='moneyger_installment_paid_gte_0')],
            },
        ),
    ]
