# Generated by Django 5.2 on 2026-09-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyger', '0003_market_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='limit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketlist',
            name='resulting_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_market_list', to='moneyger.transaction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('cash', 'Dinheiro'), ('credit', 'Cartão de crédito'), ('meal_voucher', 'Vale alimentação / refeição'), ('fuel_voucher', 'Vale combustível / transporte'), ('other', 'Outro')], default='checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('meal_voucher', 'Vale alimentação / refeição'), ('fuel_voucher', 'Vale combustível / transporte'), ('other', 'Outro')], default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringrule',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('meal_voucher', 'Vale alimentação / refeição'), ('fuel_voucher', 'Vale combustível / transporte'), ('other', 'Outro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credit', 'Crédito'), ('debit', 'Débito'), ('cash', 'Dinheiro'), ('meal_voucher', 'Vale alimentação / refeição'), ('fuel_voucher', 'Vale combustível / transporte'), ('other', 'Outro')], default='other', max_length=20),
        ),
    ]
