# Generated by Django 5.2 on 2026-09-22 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyger', '0004_account_limits_and_market_tx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('installment_pay', 'Pagou parcela'), ('installment_mark', 'Marcou parcela'), ('installment_undo', 'Desfez parcela'), ('transaction_account', 'Alterou conta do lançamento')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='marketlistitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketlistitem',
            name='units',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='marketlistitem',
            constraint=models.CheckConstraint(condition=models.Q(('units__gt', 0)), name='moneyger_market_item_units_positive'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='installment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='moneyger.installmentplan'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='moneyger.transaction'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='moneyger_ac_user_id_cd1cd9_idx'),
        ),
    ]
