# Generated by Django 5.2 on 2026-09-22 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyger', '0005_activity_and_market_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMarketDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('phase', models.CharField(choices=[('limit', 'Aguardando teto'), ('items', 'Recebendo itens')], default='limit', max_length=16)),
                ('pending_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_activity_at', models.DateTimeField()),
                ('warned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_drafts', to='moneyger.marketlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moneyger_market_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['last_activity_at'], name='moneyger_bo_last_ac_c03e60_idx')],
            },
        ),
    ]
