# Generated by Django 5.2 on 2026-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_and_gym_app_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moneyger_enabled',
            field=models.BooleanField(default=False, help_text='Libera o módulo Moneyger para este usuário.'),
        ),
    ]
